<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Additional tools for testing software</Description>
    <Version>1.5.2</Version>
    <Authors>wm</Authors>
    <Company>ANIXE Polska Sp. z o.o.</Company>
    <IncludeSource>True</IncludeSource>
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/wmaryszczak/anixe_qualitytools</RepositoryUrl>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>anixe;quality;tools;tests</PackageTags>
    <PackageProjectUrl>https://www.nuget.org/packages/Anixe.QualityTools</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="ConsoleMenu-simple" Version="2.7.0" />
    <PackageReference Include="FluentAssertions.Json" Version="6.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="FluentAssertions" Version="7.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <Target Name="SetPackageReleaseNotes" BeforeTargets="GenerateNuspec">
    <PropertyGroup>
      <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/CHANGELOG.md"))</PackageReleaseNotes>
    </PropertyGroup>
  </Target>
</Project>